version: "3.8"
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: northwind_db
      POSTGRES_USER: northwind_admin
      POSTGRES_PASSWORD: northwind123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
